spring.application.name=Bank
server.port=8274
spring.datasource.url=jdbc:h2:mem:hr
spring.datasource.username=HRAnsari
spring.sql.init.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true